### ISSUE TITLE
In Threading mode URL Router "Freezes" on 404 or "/"

### ISSUE THREAD

**Issue by gustavogalvan** [risoflora/brookframework#47] opened 2023-03-09 14:17 UTC
Maybe I found the problem in **BrookURLRouter.pas**, in procedure **TBrookURLRouter.Route**.
I put two **FLocker.Unlock**, one in line 102 after _R.HandleRequest(..._, and the other at the end, before _DoNotFound(..._

This is the code fragment:

```
  if B then
  begin
    DoRoute(ASender, APath, ARequest, AResponse);
    Exit;
  end;
  if APath = '/' then
  begin
    R := FRoutes.FindDefault;
    if Assigned(R) then
    begin
      R.HandleRequest(ASender, R, ARequest, AResponse);
      FLocker.Unlock; {bugfix?}
      Exit;
    end;
  end;
  DoNotFound(ASender, APath, ARequest, AResponse);
  FLocker.Unlock; {bugfix?}
end;

```
I hope this help.
Thank for your great job !

**Comment by silvioprog** [comment] 2023-03-09 17:37
Hey @gustavogalvan, thanks a lot for reporting. So, do you have some steps for how to reproduce the problem?

**Comment by silvioprog** [comment] 2023-03-12 17:14
I can't reproduce the problem. Please take a look at the log below:

```pascal
...
  with TServer.Create(nil) do
  try
    Threaded := True;
    Port := 8080; 
...
```

```bash
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/non-existing-path
Page not found
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/non-existing-path
Page not found
% curl -w '\n' http://127.0.0.1:8080/non-existing-path
Page not found
% curl -w '\n' http://127.0.0.1:8080/non-existing-path
Page not found
% curl -w '\n' http://127.0.0.1:8080/home
Home page
% curl -w '\n' http://127.0.0.1:8080/home
Home page
```

Also tried using a browser, can't find any problem.

**Comment by silvioprog** [comment] 2023-03-12 17:16
BTW your logic sounds correct, let me investigate more and let you know if can reproduce the proble.

**Comment by silvioprog** [comment] 2023-03-12 17:24
@gustavogalvan, could you provide a PR?

**Comment by gustavogalvan** [comment] 2023-03-12 21:39
Hi, I forgot mention I work in linux.

**Comment by gustavogalvan** [comment] 2023-03-12 23:40
testing again, with curl :

gustavo@MOV:~$ curl -w '\n' http://127.0.0.1:8888/non-existing-page
Page not found
gustavo@MOV:~$ curl -w '\n' http://127.0.0.1:8888/non-existing-page
^C
gustavo@MOV:~$ curl -w '\n' http://127.0.0.1:8888/non-existing-page
^C
gustavo@MOV:~$ curl -w '\n' http://127.0.0.1:8888/non-existing-page
^C
gustavo@MOV:~$ 

At the first request is ok, then remains locked.

**Comment by gustavogalvan** [comment] 2023-03-12 23:49
I followed your code to find the unlocks for that situations and not found.
Just two unlocks 
![image](https://user-images.githubusercontent.com/12851441/224581277-14b85130-0caf-4eb9-aa24-55cc77bba9a3.png)

**Comment by silvioprog** [comment] 2023-04-12 17:12
Hey @gustavogalvan, could you provide a Pull Request? If so, we can approve it and merge into master.

**Comment by gustavogalvan** [comment] 2023-04-12 22:06
Hello Silvio, I just made the pull request. I am sorry for the delay.

**Comment by silvioprog** [comment] 2023-04-13 22:52
Merged. Thanks a lot for the fix! 🙂

**Closed by silvioprog** 2023-04-13 22:52 UTC
Labels: bug
